# Site settings
name:  ThreeMen
email: 939896399@qq.com 
author: improve100 
url: http://www.threemen.tech
resume_site: http://www.threemen.tech
github: https://github.com/improve100
baseurl: ""
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: improve100
highlighter: rouge


encoding: UTF-8


# Build settings
markdown: kramdown

FB:
  comments :
    provider : improve100
    duoshuo:
        short_name : improve100
    disqus :
        short_name : improve100
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
